# Generated by Django 3.1.13 on 2024-08-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_email_recipients_alter_email_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='body',
        ),
        migrations.AddField(
            model_name='email',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='mail_through',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='mail_type',
            field=models.CharField(default='Internal', max_length=200),
        ),
        migrations.AddField(
            model_name='email',
            name='referenceCode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ExternalMailsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('mail_through', models.CharField(max_length=200)),
                ('recipients', models.CharField(max_length=200)),
                ('subject', models.TextField()),
                ('amount', models.IntegerField()),
                ('referenceCode', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='mail.departmentzoneunit')),
            ],
        ),
    ]
