# Generated by Django 3.1.13 on 2024-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20240815_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalmailsrecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='externalmailsrecord',
            name='referenceCode',
        ),
        migrations.AddField(
            model_name='externalmailsrecord',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='externalmailsrecord',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
