# Generated by Django 3.1.13 on 2024-08-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20240821_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='email',
            name='starred',
        ),
    ]
