# Generated by Django 3.1.13 on 2024-08-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20240821_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default='BZO', on_delete=django.db.models.deletion.CASCADE, to='mail.departmentzoneunit'),
        ),
    ]
