# Generated by Django 5.1 on 2024-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_remove_email_mail_type_alter_email_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
